version: '3.4'
services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:latest # Use the latest image
    ports:
      - "8080:8080" # REST API port
      - "50051:50051" # gRPC port
    volumes:
      - weaviate_data:/var/lib/weaviate # Persistent data volume
    restart: always
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none' # Or specify a module like 'text2vec-openai'

volumes:

  weaviate_data:
